/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ExpenseId = IDL.Nat;
export const Expense = IDL.Record({
  'id' : ExpenseId,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addExpense' : IDL.Func([IDL.Text, IDL.Float64, IDL.Text], [Expense], []),
  'deleteExpense' : IDL.Func([ExpenseId], [], []),
  'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ExpenseId = IDL.Nat;
  const Expense = IDL.Record({
    'id' : ExpenseId,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    'addExpense' : IDL.Func([IDL.Text, IDL.Float64, IDL.Text], [Expense], []),
    'deleteExpense' : IDL.Func([ExpenseId], [], []),
    'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };